// <auto-generated />
namespace AutoSolution.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class f : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(f));
        
        string IMigrationMetadata.Id
        {
            get { return "202004110858595_f"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
