// <auto-generated />
namespace AutoSolution.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class newsettingagain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newsettingagain));
        
        string IMigrationMetadata.Id
        {
            get { return "202003290818112_newsettingagain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
